### ISSUE TITLE
sedutil-cli: passwords on the command line are a security vulnerability

### ISSUE THREAD

**Issue by OliverO2** [sedutil/sedutil#17]
Currently, `sedutil-cli` requires passwords as command line arguments. Such passwords can easily leak into operating system files in clear text and subsequently, into backup files on less protected media:

* One example is a bash history file (use `unset HISTFILE` to protect against that).

* A more dangerous example is when `sedutil-cli` is called via `sudo`. Then its whole command line ends up in the systemd journal and `/var/log/auth.log`, where each call to `sudo` is normally logged. For systems configured to store journals persistently, it is even worse. There is no easy way to remove a single entry from the journal without losing the content of entire journal files.

`sedutil-cli` should really read passwords from stdin at all times. See [this example](https://stackoverflow.com/questions/1413445/reading-a-password-from-stdcin).

**Comment by OliverO2** [comment]
Project discontinued.

**Comment by cristim** [comment]
@OliverO2 I still see the same situation as when this project was created, no new commits from DTA in years and tons of diverging individual forks without a clear maintained mainline. Soon after this project was created and started getting some contributions DTA dropped a lot of new code that rendered this project outdated and we failed to rebase it on their recent code, but at least it resulted in that last release.

Ideally the people who maintain all these forks would come together and work on a shared code base under this repository, to at least cause DTA to develop in the open, or even offer additional functionality.

I'm no longer running sedutil but I will gladly grant access to the sedutil Github organization to whoever wants to step up to maintain this project in the open.

@lorak-mmk, @amotin, @miurahr, @andrewMeir, @jpsollie, @kraj, @kirgene, @bill-wright, @hurufu let me know if any of you are interested.

**Comment by OliverO2** [comment]
@cristim I guess Linux users can live with the current situation if they
* use just the low-level command line tool `sedutil-cli` from [DTA](https://github.com/Drive-Trust-Alliance/sedutil), and
* use [Relax-and-Recover](https://github.com/rear/rear) to obtain
    * an up-to-date PBA (supporting localized keyboards, BIOS, UEFI and secure boot),
    * a rescue system and
    * an easy-to-use (and safe) tool for administrative tasks.

There is a complete guide explaining everything. It includes a section "[Quick Start: Setting up Self-Encrypting Disks](https://github.com/rear/rear/blob/master/doc/user-guide/13-tcg-opal-support.adoc#quick-start-setting-up-self-encrypting-disks)".

**Comment by cristim** [comment]
Fair enough, thanks! I know about rear, it does indeed take care of a lot of things.

If the sedutil community is happy with the current state of affairs, that's fine with me, as I said I'm no longer using it.

**Comment by amotin** [comment]
@cristim I would happily commit into shared project rather than my own fork.  I suppose we just need consensus what shall it be if not DTA.

**Comment by miurahr** [comment]
@amotin @cristim

 I've looked here and understand it as discontinued, then I've started  investigating Linux related part of sedutil as my public project https://github.com/miurahr/sedutil-linux

If you willing to continue the project for Linux users as shared/public one, my fork may be a candidate for  reference.

**Comment by cristim** [comment]
@miurahr as I said above, I have no interest and bandwidth in maintaining this project, but I can transition the sedutil organization to anyone willing to do it and the sedutil/sedutil repo could easily be updated to become a reference mainline repo.

**Comment by AndrewMeir** [comment]
Thanks for your comments @cristim . I'm inclined to agree, especially with this one:

> Ideally the people who maintain all these forks would come together and work on a shared code base under this repository, to at least cause DTA to develop in the open, or even offer additional functionality.

I don't have a lot of spare bandwidth but I'll help in any way that I can.
