### ISSUE TITLE
autobuild.sh complete aborts in ./buildUEFI64

### ISSUE THREAD

**Issue by OliverO2** [sedutil/sedutil#18]
Originally reported by @davidepic91 in [this comment](https://github.com/Drive-Trust-Alliance/sedutil/issues/159#issuecomment-315316856).

Error message:
`./buildUEFI64: line 39: scratch/buildroot/PBA64/overlay/etc/init.d/rcS: No such file or directory`

**Comment by OliverO2** [comment]
Seems that the error appears if there has never been a build with a non-US keyboard before.

@davidepic91 could you please replace the contents of images/buildUEFI64 with [this fixed version](https://gist.github.com/OliverO2/6ad1f7ce0e639c14108ce263ac911877)?

Then, please continue with
```
sudo docker run --rm -it -v $PWD/../:/sedutil --privileged sedutil /sedutil/images/autobuild.sh images dist
```

Does that work for you?

**Comment by davidepic91** [comment]
Yes ! With [this fixed version](https://gist.github.com/OliverO2/6ad1f7ce0e639c14108ce263ac911877) it works !

**Comment by cristim** [comment]
That's great, please make a PR with that fix, I'll gladly approve it.
